### PR TITLE
close #42 Update to draw MultiPolygon

### LINKED ISSUE #42: Multi-part polygons are never drawn.
I have tried some geojsons to draw by L.glify, and realize some shapes are never drawn if they are multi-part.
When one geojson has some multi-part shapes and some single-part shapes, only single-part shapes are drawn.

### PR DESCRIPTION
**Pull request by Kanahiro**
I added some codes to correctly process multi-part polygon.

Despite MultiPolygon Geojson is not same structure to Polygon one, glify process these two type of Geojsons in ONE way as same structure. Because of this, MultiPolygon Geojson is never drawn by this plugin.
The codes I added solve this problem by dealing with two type of Geojsons in different way,

Addition, same problem is in lines.js. I also added some codes to solve.

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
I will look at this soon, sorry, been busy.

**Comment by robertleeplummerjr** [comment]
I've since migrated to typescript.  Can you reevaluate, and see if porting this functionality can be done?

**Comment by Kanahiro** [comment]
Ok, I'll check it.
I think, this PR should be closed once and re-write some codes for TypeScript version. Don't you?

**Comment by robertleeplummerjr** [comment]
I think so.

**Pull request closed without merging**
