### PR TITLE
#48

### PR DESCRIPTION
**Pull request by adiityasharrma**
Added functionality to provide size as a Function for Points

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Lol, I just got done doing almost the same thing!  Great minds.

**Comment by adiityasharrma** [comment]
Hi @robertleeplummerjr 
When i am using your updated code of glify.js and giving size as a function
complete array of point are not rendering on map
instead it is rendering only fixed index of points(indexes like 0,5,10,15 and so on).

**Comment by adiityasharrma** [comment]
I think we need to change bytes from 5 to 6 as we have converted the verts array to 6.

**Comment by robertleeplummerjr** [comment]
I think you are right.  You want to open a PR?

**Comment by adiityasharrma** [comment]
> I think you are right. You want to open a PR?

PR?

**Comment by adiityasharrma** [comment]
> I think you are right. You want to open a PR?

I have open a PR #52 .

**Pull request merged**
