### PR TITLE
Updated byte from 5 to 6 for Size function

### PR DESCRIPTION
**Pull request by adiityasharrma**
Updated byte from 5 to 6 for Size function implementation for points

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Can you add changes to the points.js file, and use `yarn build` so they propagate to the glify.js file?

**Comment by adiityasharrma** [comment]
@robertleeplummerjr 
Sure, i'll do that

**Comment by robertleeplummerjr** [comment]
Nice work!

**Comment by robertleeplummerjr** [comment]
Published.

**Comment by adiityasharrma** [comment]
> Nice work!

Thanks Robert.
Appreciate your work for creating this amazingly fast library.

**Pull request merged**
