### PR TITLE
Line support was added

### PR DESCRIPTION
**Pull request by sashuk**
lines

### CODE REVIEW

**Comment by sashuk** [comment]
@robertleeplummerjr Thank you very much to you for this library!

**Comment by kkdd** [comment]
Thank you for your work. It was an eager waiting functionality for me.
I wonder, however, that I observe it consumes relatively long time for adding lines to a map, compared with the present fast performance of adding points.

**Comment by robertleeplummerjr** [comment]
Can you share a use case, we'll iron out the issue.

**Comment by tim-salabim** [comment]
@sashuk is there a way to control line width?

**Comment by sashuk** [comment]
@tim-salabim Hello! Seems like it is not supported out of the box, the line has to be rasterized, basically converted to a number of triangles (more at https://mattdesl.svbtle.com/drawing-lines-is-hard)

**Comment by robertleeplummerjr** [comment]
Or, we could draw it a few times in a range of area, like a brush.

**Comment by kkdd** [comment]
Hello,
I ran a benchmark test (see below) on google chrome and got the following result:

> number of vertecies in lines = 100 * 10; adding to map; 39 ms
> number of vertecies in lines = 1000 * 10; adding to map; 481 ms
> number of vertecies in lines = 10000 * 10; adding to map; 56102 ms   <== (long time)
> number of vertecies in lines = 1000 * 100; adding to map; 6397 ms
> number of vertecies in lines = 100 * 1000; adding to map; 818 ms
> number of vertecies in lines = 10 * 10000; adding to map; 246 ms


The following is my test code:

```js
var RE = 6378137.0, KM = 1000, DEGREE = Math.PI / 180;
var center = [50.00, 14.44], radius = 100 * KM, nvertex = [10, 10000];

radius = radius / RE / DEGREE;
radius = [radius, radius / Math.cos(center[0]*DEGREE)]

var line, lines = [], delta = [];
for (var i = 0; i < nvertex[0]; i++) {
	line = [];
	for (var j = 0; j < nvertex[1]; j++ ) {
		delta = [(Math.random()*2-1)*radius[0], (Math.random()*2-1)*radius[1]];
		line.push([center[0]+delta[0], center[1]+delta[1]]);
	}
	lines.push({"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates": line}});
}

var start = new Date().getTime();
L.glify.lines({
  map: map,
  longitudeKey: 1,
  latitudeKey: 0,
  data: {"type":"FeatureCollection","features":lines},
  color: function(i, w) {return {"r":1, "g":0, "b":0};}
});
var elapsed = new Date().setTime(new Date().getTime() - start);
console.log(`number of vertecies in lines = ${nvertex[0]} * ${nvertex[1]}; adding to map; ${elapsed} ms`);
```

leafletglify

**Comment by robertleeplummerjr** [comment]
Lets open a new issue about performance, since this issue has been reasonably solved.

**Comment by robertleeplummerjr** [comment]
Added here: https://github.com/robertleeplummerjr/Leaflet.glify/issues/23

**Pull request merged**
