### PR TITLE
CATCHALL: bump all deps to latest, consolidate all PR's into one

### PR DESCRIPTION
**Pull request by charlieforward9**
Closes #115, Closes #116, Closes #118, Closes #123, Closes #126, Closes #127, Closes #130, Closes #135, Closes #136, Closes #138, Closes #140, Closes #142, Closes #143, Closes #144, Closes #145, Closes #147, Closes #149, Closes #153, Closes #155

I needed this to work with Leaflet 1.9.4, so I decided to make sure it WORKED. 

There may be slight regression in coverage with all the existing feature PRs I included. However, all the unit tests pass on my machine. I encourage the contributors of the features to add unit tests if they havent, so I can merge them in.

Took a while to get my config set up to get everything running, specifically with the `canvas` dependency. Seems like running this on  silicon takes some extra lifting. (It may have also been an issue that I used the migration manager from an x86 archi so I needed to reset my Node/Homebrew to work exclusively with arm-based deps)

### CODE REVIEW

**Comment by charlieforward9** [comment]
@robertleeplummerjr please review this!

**Comment by robertleeplummerjr** [comment]
Great work.  I'll get a release published ASAP.

**Comment by robertleeplummerjr** [comment]
Published https://www.npmjs.com/package/leaflet.glify/v/3.3.0

**Comment by tim-salabim** [comment]
Thanks Robert! This is awesome news

**Comment by melgrove** [comment]
@charlieforward9 @robertleeplummerjr What a pleasant surprise seeing this in my inbox this morning! Amazing work consolidating this PR and publishing the release :)

**Comment by RayLarone** [comment]
Thanks all 🙌 This is such a great plugin! :)

Just a heads-up: this latest version should now also close/resolve #119 and possibly #54

**Pull request merged**
