### PR TITLE
Make leaflet a peer dependency / webpack external

### PR DESCRIPTION
**Pull request by danwild**
This PR is to address #98.

Example:
- [Conflicts before fix](https://gist.github.com/danwild/bad25212abb326b9d55179c4a22ee006)
- [Conflicts resolved after refactor](https://gist.github.com/danwild/7a843b6ed8b686725ae476162da502f2) (using a webpack build @[a2a6acd](https://github.com/danwild/Leaflet.glify/commit/a2a6acd2392e1619e1bbc2bd7aa95deb69954db6))

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
I had started refactoring to a stricter typescript and unit testing over the weekend, and just committed it.  However, just before doing so, I implemented your recommendations, TY!  I'll close this PR, but awesome recommendation that I tried my best to accredit to you.

**Comment by danwild** [comment]
No worries, thanks for folding this in @robertleeplummerjr  👍

Just a heads up tho - in [current master](https://github.com/robertleeplummerjr/Leaflet.glify/blob/2e4ca2fb8a66ea195a110ce39316b8497206af25/package.json) the leaflet dependency is in both `dependencies` and `peerDependencies`

**Comment by robertleeplummerjr** [comment]
Fixed and pushed.

**Comment by danwild** [comment]
Great - looking forward to npm release of `v3.2.0`

**Comment by danwild** [comment]
Hi - @robertleeplummerjr curious to know if there will likely be an npm release for `v3.2.0` any time soon?

**Pull request closed without merging**
